<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL_formGroupEmail (1)</name>
   <tag></tag>
   <elementGuidId>b69d049e-a367-46bf-835a-2130ae7fa39a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGroupEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGroupEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da8d53a1-3dcd-4e34-91b4-400be3d1e78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c0874cef-dde9-466c-88ed-0c42dc1167d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupEmail</value>
      <webElementGuid>d2434bcd-83a3-4ed6-b812-afbb14ba77b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_field__1VXib form-control</value>
      <webElementGuid>b8bfdb29-7e4a-457d-9bdb-6df3e674d476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>0cec1177-74e3-403b-9d7b-fafd94b1f8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGroupEmail&quot;)</value>
      <webElementGuid>aa91df13-3253-4102-bdf0-15cf048a16ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGroupEmail']</value>
      <webElementGuid>37aa79ad-497a-4124-b12a-ed15df706ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/div/input</value>
      <webElementGuid>18cd9a7f-c4a5-493d-ba17-18de782265ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a2f7beca-eb8d-429a-9f1a-06858a7785d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'formGroupEmail']</value>
      <webElementGuid>2aa9f42e-995b-4332-bd6b-262c8ed2e6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
