<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PASSWORD_formGroupPassword</name>
   <tag></tag>
   <elementGuidId>fc68ec24-cd97-4735-b39f-7f6ef756eb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGroupPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGroupPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33dc572d-c1ff-4246-80d5-63071c9cc3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>76634557-f2ef-43f1-afe8-b2263d9ca033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupPassword</value>
      <webElementGuid>15a8ecda-5c3e-4824-9d08-18e07af8b3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_field__1VXib form-control</value>
      <webElementGuid>5bd82b3b-8c8a-4ff6-ad9c-409d549e3ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGroupPassword&quot;)</value>
      <webElementGuid>5ecffee3-1e79-4559-9fe0-0f8824342e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGroupPassword']</value>
      <webElementGuid>05f711ff-6b85-41b4-b755-4238b6e61341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>66101116-6d74-4137-a022-5aba0f3ab81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>866532f7-d91b-4474-8fcd-e6070aed9c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formGroupPassword']</value>
      <webElementGuid>7241363b-63b3-4e2f-852b-9d165a65a6f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
