<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL_formGroupEmail</name>
   <tag></tag>
   <elementGuidId>15b197c1-6c7c-43bd-808a-7101beea03b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGroupEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGroupEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b71a2ff-f687-4349-9dba-3b17962c9ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>70498a39-7d55-4497-9865-f99b53a7e242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupEmail</value>
      <webElementGuid>afbb4835-5871-4e89-b642-80ffb2157123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_field__1VXib form-control</value>
      <webElementGuid>6cbd1f0d-e8e2-489a-9255-75d525b1ca72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>1dd86b39-2b47-44c7-bf8b-ee96a2d81459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGroupEmail&quot;)</value>
      <webElementGuid>17096c97-9e44-49fe-bfea-5ff7ee91d7cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGroupEmail']</value>
      <webElementGuid>34474d9d-d5d8-4ebf-979e-ddd34435868b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/div/input</value>
      <webElementGuid>9ab4c652-32bf-42b0-9f45-12f2491e1f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8f9ee81f-0378-42bd-b910-a60418308dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'formGroupEmail']</value>
      <webElementGuid>37310006-bdc4-4356-aa24-10fa472f765e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
