<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PASSWORD_formGroupPassword (1)</name>
   <tag></tag>
   <elementGuidId>7b0895b8-ef8c-4cdf-97ba-63c23d5c66d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formGroupPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formGroupPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d981aa4-17a7-4a73-9ba0-83d6967ac2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>30c37f16-37fd-494f-aabf-584721083ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formGroupPassword</value>
      <webElementGuid>8536855e-0e0b-46fc-8602-ac815cc1d493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_field__1VXib form-control</value>
      <webElementGuid>8e37ccc2-d7a6-4ac7-bcd8-733d9829eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formGroupPassword&quot;)</value>
      <webElementGuid>b5623bec-84eb-4c90-83d6-dcd920e52a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formGroupPassword']</value>
      <webElementGuid>a10e3beb-7f16-47d4-b625-f78da8e71c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>879ee569-fa83-4c62-83e7-d52d66c9d6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>335d2717-0d7f-411d-b645-6f243296622d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'formGroupPassword']</value>
      <webElementGuid>5ffce9e8-096c-4949-b604-f7723c913eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
