<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>dbcfbf9f-2c2c-4e5d-aabe-bfada9d582e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button_primaryButton__3QuSp.btn.btn-primary > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8db616ca-8b5f-4d96-9bc5-918d70564db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e0daf4be-2f41-459e-a771-fd15ab2efc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_loading_overlay_wrapper css-79elbk&quot;]/div[@class=&quot;app-body&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;h-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;auth-container col-lg-5&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-9&quot;]/div[@class=&quot;form-container&quot;]/div[1]/div[@class=&quot;col&quot;]/form[1]/button[@class=&quot;button_primaryButton__3QuSp btn btn-primary&quot;]/span[1]</value>
      <webElementGuid>539d54c6-f0fa-4218-8cd7-5003ab173644</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div[2]/div/div/div/form/button/span</value>
      <webElementGuid>28034b74-e520-4555-a8dd-19b81fac1d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASSWORD'])[1]/following::span[2]</value>
      <webElementGuid>9a462305-10a4-4cc9-835f-da38b4112349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMAIL'])[1]/following::span[2]</value>
      <webElementGuid>aadedd93-61ef-4e18-9f5d-76651c7f7112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::span[1]</value>
      <webElementGuid>46415aa5-4c08-401d-9d8c-a1cc3061a448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>0df1df7d-8f7f-41c3-85b1-3c838cef7465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>18380c91-5789-4c6d-816b-17e1fc8cab40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>96be48c1-0616-4e1d-9aef-ab2a0b2d34c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
